// AUTO-GENERATED by tools/Qualification/generate_mobile_contracts.py.
// DO NOT EDIT BY HAND — regenerate and run `--check` in CI.
// V1R5 §4: single source of truth for evidence input limits.
import Foundation

enum GeneratedMobileEvidenceContracts {
    static let contractVersion = 1
    static let wave = "mobile-only-v1r5-field-qualification-integrity-scale-closeout"

    enum ProductScale {
        static let maxRawNodes = 60000
        static let maxTagObservations = 200000
        static let maxClockNodeBindings = 60000
        static let scanHoursUpperBound = 48
    }

    enum File_clock_correlations_jsonl {
        static let blank_line_policy = "reject"
        static let final_newline = true
        static let identity_fields: [String] = ["tracking_session_id"]
        static let max_file_bytes = 268435456
        static let max_nesting_depth = 8
        static let max_record_bytes = 1048576
        static let max_records = 1000000
        static let strict_bool = true
        static let strict_integer = true
        static let watermark_fields: [String] = ["clockCorrelationCount", "clockNodeBindingCount"]
    }

    enum File_localization_constraints_jsonl {
        static let blank_line_policy = "reject"
        static let final_newline = true
        static let identity_fields: [String] = ["priorMapId", "priorMapSha256", "trackingSessionId", "floorId"]
        static let max_file_bytes = 805306368
        static let max_nesting_depth = 8
        static let max_record_bytes = 65536
        static let max_records = 400000
        static let qualification_max_records = 345600
        static let qualification_record_rate_hz = 2
        static let strict_bool = true
        static let strict_integer = true
        static let watermark_fields: [String] = ["captureHealth.localizationConstraintRecordCount"]
    }

    enum File_localization_trace_jsonl {
        static let blank_line_policy = "reject"
        static let final_newline = true
        static let identity_fields: [String] = ["trackingSessionId", "priorMapId", "priorMapSha256", "floorId"]
        static let max_file_bytes = 536870912
        static let max_nesting_depth = 8
        static let max_record_bytes = 1048576
        static let max_records = 2000000
        static let qualification_max_records = 1728000
        static let qualification_record_rate_hz = 10
        static let strict_bool = true
        static let strict_integer = true
        static let watermark_fields: [String] = ["captureHealth.localizationTraceRecordCount"]
    }

    enum File_manual_localization_events_jsonl {
        static let blank_line_policy = "reject"
        static let final_newline = true
        static let identity_fields: [String] = ["prior_map_id", "prior_map_sha256", "tracking_session_id", "floor_id"]
        static let max_file_bytes = 67108864
        static let max_nesting_depth = 8
        static let max_record_bytes = 1048576
        static let max_records = 100000
        static let strict_bool = true
        static let strict_integer = true
        static let watermark_fields: [String] = ["captureHealth.manualLocalizationEventCount"]
    }

    enum File_metadata_json {
        static let blank_line_policy = "n_a"
        static let final_newline = false
        static let identity_fields: [String] = ["storeId", "floorId", "priorMapId", "priorMapSha256", "trackingSessionId"]
        static let max_file_bytes = 1048576
        static let max_nesting_depth = 8
        static let max_record_bytes = 1048576
        static let max_records = 1
        static let strict_bool = true
        static let strict_integer = true
        static let watermark_fields: [String] = ["finalized", "clockCorrelationCount", "clockNodeBindingCount", "tagObservationBurstCount", "tagObservationBurstLastID", "tagObservationBurstComplete", "captureHealth.localizationTraceRecordCount", "captureHealth.localizationConstraintRecordCount", "captureHealth.manualLocalizationEventCount", "captureHealth.localizationRecoveryEventCount"]
    }

    enum File_native_graph {
        static let max_factors = 4096
        static let max_priors = 4096
        static let max_raw_nodes = 200000
        static let max_skeleton_nodes = 4096
        static let max_trajectory_rows = 200000
    }

    enum File_result_package {
        static let immutable = true
        static let max_manifest_bytes = 4194304
        static let max_package_files = 64
        static let max_per_file_bytes = 2147483648
        static let package_sha256 = true
        static let per_file_sha256 = true
    }

    enum File_scan_events_jsonl {
        static let blank_line_policy = "reject"
        static let final_newline = true
        static let identity_fields: [String] = ["trackingSessionId"]
        static let max_file_bytes = 268435456
        static let max_nesting_depth = 8
        static let max_record_bytes = 1048576
        static let max_records = 1000000
        static let strict_bool = true
        static let strict_integer = true
        static let watermark_fields: [String] = []
    }

    enum File_tag_observation_bursts_jsonl {
        static let blank_line_policy = "reject"
        static let final_newline = true
        static let identity_fields: [String] = ["tracking_session_id", "floor_id"]
        static let max_file_bytes = 268435456
        static let max_nesting_depth = 8
        static let max_record_bytes = 4194304
        static let max_records = 200000
        static let strict_bool = true
        static let strict_integer = true
        static let watermark_fields: [String] = ["tagObservationBurstCount", "tagObservationBurstLastID", "tagObservationBurstComplete"]
    }

    enum File_tag_observations_jsonl {
        static let blank_line_policy = "reject"
        static let final_newline = true
        static let identity_fields: [String] = ["prior_map_id", "prior_map_sha256", "tracking_session_id", "floor_id"]
        static let max_file_bytes = 268435456
        static let max_nesting_depth = 8
        static let max_record_bytes = 1048576
        static let max_records = 200000
        static let strict_bool = true
        static let strict_integer = true
        static let watermark_fields: [String] = ["tagObservationBurstCount", "tagObservationBurstLastID", "tagObservationBurstComplete"]
    }

    enum File_xlsx_workbook {
        static let crc_and_size_verified = true
        static let exact_four_sheets = true
        static let max_file_bytes = 2147483648
        static let max_sheet_rows = 500000
        static let no_formula = true
    }

}
